### ISSUE TITLE
default password ?

### ISSUE THREAD

**Issue by wings-of-gold** [hdavid0510/docker-ubuntu-lxde-novnc#12]
default password ?

**Comment by hdavid0510** [comment]
If you have not set `USER`, `PASSWORD`, `VNC_PASSWORD` in environment variables, then the default password should be blank(undefined). You may:
  - run `passwd` in commandline to set password inside the container already running, or
  - create a container with the environment variable `PASSWORD` with the password you want, and let the password be set during the initial setup process.
For further information, please refer to the [README.md in this repository](https://github.com/fcwu/docker-ubuntu-vnc-desktop#default-desktop-user), where this repository is based on.

**Comment by hdavid0510** [comment]
If you have not set `USER`, `PASSWORD`, `VNC_PASSWORD` in environment variables, then the default password should be blank(undefined). You may:
  - run `passwd` in commandline to set password inside the container already running, or
  - create a container with the environment variable `PASSWORD` with the password you want, and let the password be set during the initial setup process.
For further information, please refer to the [README.md in this repository](https://github.com/fcwu/docker-ubuntu-vnc-desktop#default-desktop-user), where this repository is based on.

**Comment by FLL-SELF** [comment]
> If you have not set `USER`, `PASSWORD`, `VNC_PASSWORD` in environment variables, then the default password should be blank(undefined). You may:
> 
> * run `passwd` in commandline to set password inside the container already running, or
> * create a container with the environment variable `PASSWORD` with the password you want, and let the password be set during the initial setup process.
>   For further in, please refer to the [README.md in this repository](https://github.com/fcwu/docker-ubuntu-vnc-desktop#default-desktop-user), where this repository is based on.
